### ISSUE TITLE
Question: Blendmap / Splatmap

### ISSUE THREAD

**Issue by Gusher** [tomankirilov/VPainter#8]
Does it save the blendmap / splatmap after painting? Already supports 4 texture blendintg RGBA? Looks very impressive..

**Comment by tomankirilov** [comment]
All the addon does is that it paints vertex color on a mesh. The shader for blending textures is there just for demonstration. 
Since you have to modify the mesh itself in order to save new data (the vertex color in that case) the mesh gets duplicated. You can always save it as a new resource or over the original mesh.

**Comment by Gusher** [comment]
So in a sense it does save the blend which is on the mesh then can be extracted with 3rd party tools like blender or 3dsmax... ? Would be awesome to be able to render the vertex map to texture right inside GODOT, unless someone else already has an addon that does that.... data extraction from mesh..

**Comment by tomankirilov** [comment]
That would be a totally different addon as far I can tell. At the moment the only thing it does it to edit vertex color and save it as a Godot mesh. I don't think it is planned to render it to a texture.
Also the tools you mentioned can edit vertex colors anyway. I can't really see why would you want to import it back there. The point of VPainter is to not do that.
